services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mkapu_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_service:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - AUTH_DB_HOST=mysql_db
      - AUTH_DB_PORT=3306
      - AUTH_DB_USERNAME=root
      - AUTH_DB_PASSWORD=root
      - AUTH_DB_DATABASE=mkp_administracion
      - PORT=3001
      - JWT_SECRET=mkapu_secret_2025
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - mkapu_network

  admin_service:
    build:
      context: .
      dockerfile: ./apps/administration/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - ADMIN_DB_HOST=mysql_db
      - ADMIN_DB_PORT=3306
      - ADMIN_DB_USERNAME=root
      - ADMIN_DB_PASSWORD=root
      - ADMIN_DB_DATABASE=mkp_administracion
      - PORT=3002
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - mkapu_network

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:3001
      - ADMIN_SERVICE_URL=http://admin_service:3002
      - SALES_SERVICE_URL=http://sales_service:3003
      - LOGISTICS_SERVICE_URL=http://logistics_service:3005
      - PORT=3000
    depends_on:
      - auth_service
      - admin_service
      - sales_service
      - logistics_service
    networks:
      - mkapu_network

  logistics_service:
    build:
      context: .
      dockerfile: ./apps/logistics/Dockerfile
    ports:
      - "3005:3005" # HTTP para el Gateway
      - "3004:3004" # TCP para la comunicaci√≥n con Ventas
    environment:
      - LOGISTICS_DB_HOST=mysql_db
      - LOGISTICS_DB_PORT=3306
      - LOGISTICS_DB_USERNAME=root
      - LOGISTICS_DB_PASSWORD=root
      - LOGISTICS_DB_DATABASE=mkp_logistica
      - PORT=3005
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - mkapu_network

  sales_service:
    build:
      context: .
      dockerfile: ./apps/sales/Dockerfile
    ports:
      - "3003:3003" # Ventas se queda con el 3003 HTTP
    environment:
      - SALES_DB_HOST=mysql_db
      - SALES_DB_PORT=3306
      - SALES_DB_USERNAME=root
      - SALES_DB_PASSWORD=root
      - SALES_DB_DATABASE=mkp_ventas 
      - PORT=3003   # Puerto interno HTTP
      - LOGISTICS_HOST=logistics_service
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - mkapu_network

networks:
  mkapu_network:
    driver: bridge